Feature/nfc implementation
JamiuJimoh/HNG_CheckNGo pull request #8
Opened 2024-07-28 22:07 UTC by Kellytomi

Added NFC Config for iOS

2024-07-28 23:58 UTC, JamiuJimoh requested changes
Can you please first pull to fix the conflict please. I thought I already merged my PR yesterday. Turns out I didn't. I made changes like the "nfc_write_page.dart" doesn't exist anymore. Please pull before creating a PR

2024-07-29 10:02 UTC, Kellytomi commented
Fixed

2024-07-29 10:02 UTC, Kellytomi commented
Fixed

2024-07-29 10:20 UTC, JamiuJimoh approved these changes

2024-07-29 10:20 UTC, merged